### ISSUE TITLE
bro wtf

### ISSUE THREAD

**Issue by TouchFa1th** [Joseloll/Webhook-Checker-Deleter#1]

**Comment by TouchFa1th** [comment]
what the fick is that Capitalization On The Start Of Every Message

like

neighbor is you homeless

**Comment by Joseloll** [comment]
Who are you random

**Comment by TouchFa1th** [comment]
hi
send the link to ur server

trash pfp

**Comment by Joseloll** [comment]
Who are you

**Comment by Joseloll** [comment]
Don’t have a server
